name: Bug Report
description: Report a reproducible problem in Claw-Empire.
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce it.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: A concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Exact steps to reproduce the issue.
      placeholder: |
        1. Run ...
        2. Open ...
        3. Click ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant logs, stack traces, or screenshots.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: App version/tag/commit hash.
      placeholder: v1.2.0 / main@abcdef1
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS
        - Linux
        - Windows
        - Other
  - type: input
    id: node
    attributes:
      label: Node.js Version
      placeholder: v22.x
